version: "3.9"
services:
  signaling:
    build: ./
    ports:
      - 4000:4000
  
  hls:
    build: ./hls
    ports:
      - 5000:5000
    # volumes:
    #   - ./hls/output:/usr/src/app/output
    environment:
      - ENDPOINT='http://signaling:4000'
    depends_on:
      - "signaling"
    command: ["./wait-for-it.sh", "signaling:4000", "--", "npm", "run", "hls"]

  client: 
    build: ./client
    ports:
      - 3000:3000